version: '3'

services:
    graphql_server:
        image: microservicesforeveryone/data_locality_base
        build: docker/base
        volumes:
            - ./:/opt
        ports:
            - 8080:80
        command: php -S 0.0.0.0:80 src/ApiEndpoints/GraphQL/server.php

    graphql_client:
        image: microservicesforeveryone/data_locality_base
        volumes:
            - ./:/opt
        command: php src/ApiEndpoints/GraphQL/client.php
        depends_on:
            - graphql_server

    rest_server_backend:
        image: microservicesforeveryone/data_locality_base
        volumes:
            - ./:/opt
        ports:
            - 8081:80
        command: php -S 0.0.0.0:80 src/ApiEndpoints/REST/server.php

    rest_client:
        image: microservicesforeveryone/data_locality_base
        volumes:
            - ./:/opt
        command: php src/ApiEndpoints/REST/client.php
        depends_on:
            - rest_server_backend

    rest_server:
        image: million12/varnish
        volumes:
            - ./varnish/config/default.vcl:/etc/varnish/default.vcl
        ports:
            - 8082:80
        depends_on:
            - rest_server_backend

    rest_client_with_network_cache:
        image: microservicesforeveryone/data_locality_base
        volumes:
            - ./:/opt
        command: php src/NetworkCache/client.php
        depends_on:
            - rest_server

    rest_client_with_client_cache:
        image: microservicesforeveryone/data_locality_base
        volumes:
            - ./:/opt
        command: php src/ClientCache/client.php
        depends_on:
            - rest_server_backend

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            # management UI:
            - 15672:15672

    redis:
        image: redis:3.2

    domain_events_producer:
        image: microservicesforeveryone/data_locality_base
        volumes:
            - ./:/opt
        command: php src/DomainEvents/producer.php
        depends_on:
            - rabbitmq

    domain_events_consumer:
        image: microservicesforeveryone/data_locality_base
        volumes:
            - ./:/opt
        command: php src/DomainEvents/consumer.php
        depends_on:
            - rabbitmq
            - redis
