version: '3'

services:
    api_endpoints_server:
        image: microservices-for-everyone/data_locality_base
        build: docker/base
        volumes:
            - ./:/opt
        ports:
            - 8080:80
        command: php -S 0.0.0.0:80 -t src/ApiEndpoints/server/

    api_endpoints_client:
        image: microservices-for-everyone/data_locality_base
        volumes:
            - ./:/opt
        command: php src/ApiEndpoints/client.php
